apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.name }}
  labels:
    app: {{ .Values.mariadb.app }}
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mariadb.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadb.app }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        {{- if and (not .Values.mariadb.openshift) (not (.Capabilities.APIVersions.Has "security.openshift.io/v1")) }}
        {{- if .Values.mariadb.fsGroup }}
        fsGroup: {{ .Values.mariadb.fsGroup }}
        {{- end }}
        {{- end }}
      automountServiceAccountToken: false
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        {{- if .Values.initSchema.enabled }}
        - name: mariadb-schema
          configMap:
            name: mariadb-schema
        {{- end }}
      containers:
        - name: {{ .Values.mariadb.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.mariadb.image }}:{{ .Values.mariadb.tag }}"
          imagePullPolicy: {{ .Values.mariadb.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mariadb.port }}
              name: {{ .Values.mariadb.name }}
          env:
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.db | quote }}
            - name: MARIADB_USER
              value: {{ .Values.mariadb.user | quote }}
            - name: MARIADB_PASSWORD
              value: {{ .Values.mariadb.password | quote }}
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword | quote }}
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
            {{- if .Values.initSchema.enabled }}
            - name: mariadb-schema
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql
            {{- end }}
